app:
  models:
    embedding:
      type: "huggingface"
      model: "BAAI/bge-large-en-v1.5"
    llm:
#      type: "huggingface"
#      model: "meta-llama/Llama-2-13b-chat-hf"
#      type: "sparkllm"
#      type: "ollama"
#      model: "qwen2.5"
      type: "gemini"
      model: "gemini-2.0-flash-exp"
#      type: anthropic
#      model: claude-3-sonnet-20240229
    chatllm:
#      type: "sparkllm"
#      type: "qwen"
#      model: "qwen2.5"
      type: "gemini"
      model: "gemini-2.0-flash-exp"
#      type: "ollama"
#      model: "llama3.1"
    rerank:
      type: "bge"
      model: "BAAI/bge-reranker-large"
  embedding:
    input_path: "./data/input"
    staging_path: "./data/staging"
    archive_path: "./data/archive"
    trunk_size: 2048
    overlap: 256
    confluence:
      url: https://akjamie.atlassian.net/
  query_agent:
    search:
      rerank_enabled: true
      web_search_enabled: true
      max_retries: 1 # max retry for query rewrite
      top_k: 10 # for retrieval top n documents, equal to max_documents
      relevance_threshold: 8.5 # for filter out low relevance documents
      query_rewrite_enabled: true
    grading: # for fact checking, the lower of the score, the higher risk of hallucination
      minimum_score: 0.7
    output:
      generate_suggested_documents: true
      generate_citations: true
    metrics:
      enabled: true
      store_in_db: true
      log_level: "INFO"
  proxy:
    enabled: true
    no_proxy: "localhost,127.0.0.1"
    http_proxy: "http://127.0.0.1:7890"
    https_proxy: "http://127.0.0.1:7890"
  logging.level:
    root: "DEBUG"  # default for all packages including project and libraries
    utils.lock: "WARNING"
    langchain: "WARNING"
    httpx: "WARNING"
